FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de configuration d'abord pour mettre en cache les couches
COPY package*.json .npmrc ./

# Installer les dépendances avec les configurations appropriées
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Construire l'application pour la production
RUN npm run build

# Installer un serveur léger pour servir l'application construite
RUN npm install -g serve

# Exposer le port
EXPOSE 3000

# Démarrer le serveur
CMD ["serve", "-s", "build", "-l", "3000"]