version: '3'

services:
  # Service frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    networks:
      - app-network

  # Service backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/calendar-app
      - JWT_SECRET=secret_dev_jwt
      - JWT_EXPIRE=7d
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - app-network

  # Service MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

# Définition des volumes
volumes:
  mongo-data:

# Définition des réseaux
networks:
  app-network:
    driver: bridge