[build]
builder = "NIXPACKS"
buildCommand = "npm run install-all && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
  [environments.production]
    [environments.production.deploy]
      PORT = "5000"
      NODE_ENV = "production"
      
  [environments.development]
    [environments.development.deploy]
      PORT = "5000"
      NODE_ENV = "development"
