[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "npm run install-all && NODE_OPTIONS=--openssl-legacy-provider npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
  [environments.production]
    [environments.production.deploy]
      PORT = "5000"
      NODE_ENV = "production"
      NODE_VERSION = "18.19.0"
      
  [environments.development]
    [environments.development.deploy]
      PORT = "5000"
      NODE_ENV = "development"
      NODE_VERSION = "18.19.0"