[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
  [build.args]
  NODE_ENV = "production"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = 15
timeout = 600
gracePeriod = 600

[env]
PORT = "5000"
NODE_ENV = "production"

[environments]
  [environments.production]
    [environments.production.deploy]
      PORT = "5000"
      NODE_ENV = "production"
      
  [environments.development]
    [environments.development.deploy]
      PORT = "5000"
      NODE_ENV = "development"