FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json .npmrc ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port
EXPOSE 5000

# Démarrer l'application
CMD ["node", "server.js"]